version: '3.7'
services:
  # this is the graph that will save the explains
  neo4j_explain:
    restart: on-failure
    image: neo4j:3.5.9
    # use non-standard ports for neo4j to prevent port conflicts
    ports:
      - "17474:17474"
      - "17687:17687"
    volumes:
      - explain_data:/var/lib/neo4j/data
    environment:
      # set initial password for dev environment - update for production
      - NEO4J_AUTH=neo4j/explain
      - NEO4J_dbms_connector_bolt_listen__address=:17687
      - NEO4J_dbms_connector_http_listen__address=:17474
      - NEO4J_dbms_logs_query_enabled=true
  # graph used for running explains against -- update environment variables on graphsplaining_service to use another
  neo4j_test:
    restart: on-failure
    image: neo4j:3.5.9 #-enterprise # enterprise requires a license for commercial use but perhaps ok for dev work
    # if you sign up with neo4j as a developer: https://neo4j.com/download/
    # use non-standard ports for neo4j to prevent port conflicts
    ports:
      - "27474:27474"
      - "27687:27687"
    volumes:
      - test_data:/var/lib/neo4j/data
      - test_logs:/var/lib/neo4j/logs
    environment:
      # set initial password for dev environment - update for production
      - NEO4J_AUTH=neo4j/explain
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_bolt_listen__address=:27687
      - NEO4J_dbms_connector_http_listen__address=:27474
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_dbms_logs_query_enabled=true
      - NEO4J_dbms_logs_query_threshold=100ms
      - NEO4J_dbms_logs_query_allocation__logging__enabled=true
      - NEO4J_dbms_logs_query_runtime__logging__enabled=true
      - NEO4J_dbms_logs_query_time__logging__enabled=true
      - NEO4J_dbms_logs_query_page__logging__enabled=true
  graphsplaining_service:
    restart: on-failure
    build:
      context: ./GraphsplainingService
      dockerfile: dev.Dockerfile
    depends_on:
      - neo4j_test
      - neo4j_explain
    volumes:
      - ./GraphsplainingService:/usr/src/app
    environment:
      # this is the graph that saves the explains
      - NEO4J_EXPLAIN_BOLT=bolt://neo4j_explain:17687
      - NEO4J_EXPLAIN_USER=neo4j
      - NEO4J_EXPLAIN_PASS=explain
      # this is the graph that is explained
      - NEO4J_MAIN_BOLT=bolt://neo4j_test:27687
      - NEO4J_MAIN_USER=neo4j
      - NEO4J_MAIN_PASS=explain
  graphsplaining_service_test:
    restart: on-failure
    build:
      context: ./GraphsplainingService
      dockerfile: dev.Dockerfile
    command: "npm test -- --watch"
    depends_on:
      - neo4j_test
      - neo4j_explain
    volumes:
      - ./GraphsplainingService:/usr/src/app
    environment:
      # this is the graph that saves the explains
      - NEO4J_EXPLAIN_BOLT=bolt://neo4j_explain:17687
      - NEO4J_EXPLAIN_USER=neo4j
      - NEO4J_EXPLAIN_PASS=explain
      # this is the graph that is explained
      - NEO4J_MAIN_BOLT=bolt://neo4j_test:27687
      - NEO4J_MAIN_USER=neo4j
      - NEO4J_MAIN_PASS=explain
  debug_scraper:
    restart: on-failure
    build:
      context: ./GraphsplainingLogScraper
      dockerfile: dev.Dockerfile
    depends_on:
      - neo4j_test
      - neo4j_explain
    volumes:
      - ./GraphsplainingLogScraper:/usr/src/app
      - test_logs:/neo4j_logs
    environment:
      # this is the graph that saves the explains
      - NEO4J_EXPLAIN_BOLT=bolt://neo4j_explain:17687
      - NEO4J_EXPLAIN_USER=neo4j
      - NEO4J_EXPLAIN_PASS=explain
      - LOG_TYPE=debug
  query_scraper:
    restart: on-failure
    build:
      context: ./GraphsplainingLogScraper
      dockerfile: dev.Dockerfile
    depends_on:
      - neo4j_test
      - neo4j_explain
    volumes:
      - ./GraphsplainingLogScraper:/usr/src/app
      - test_logs:/neo4j_logs
    environment:
      # this is the graph that saves the explains
      - NEO4J_EXPLAIN_BOLT=bolt://neo4j_explain:17687
      - NEO4J_EXPLAIN_USER=neo4j
      - NEO4J_EXPLAIN_PASS=explain
      - LOG_TYPE=query
  graphsplaining_ui:
    restart: on-failure
    build:
      context: ./Graphsplaining UI
      dockerfile: Dockerfile
    depends_on:
      - neo4j_explain
    ports:
      - "3000:3000"
    volumes:
      - ./Graphsplaining UI:/usr/src/app
volumes:
  # docker-compose will create these on start and they persist to keep graph data
  test_data:
  explain_data:
  test_logs:
