version: '3.7'
services:
  # this is the graph that will save the explains
  neo4j_explain:
    restart: on-failure
    image: neo4j:3.5.9
    # use non-standard ports for neo4j to prevent port conflicts
    ports:
      - "17474:17474"
      - "17687:17687"
    volumes:
      - explain_data:/var/lib/neo4j/data
    environment:
      # set initial password for dev environment - update for production
      - NEO4J_AUTH=neo4j/explain
      - NEO4J_dbms_connector_bolt_listen__address=:17687
      - NEO4J_dbms_connector_http_listen__address=:17474
      - NEO4J_dbms_logs_query_enabled=true
  # graph used for running explains against -- update environment variables on graphsplaining_service to use another
  neo4j_test:
    restart: on-failure
    image: neo4j:3.5.9
    # use non-standard ports for neo4j to prevent port conflicts
    ports:
      - "27474:27474"
      - "27687:27687"
    volumes:
      - test_data:/var/lib/neo4j/data
    environment:
      # set initial password for dev environment - update for production
      - NEO4J_AUTH=neo4j/explain
      - NEO4J_dbms_connector_bolt_listen__address=:27687
      - NEO4J_dbms_connector_http_listen__address=:27474
      - NEO4J_dbms_logs_query_enabled=true
      - NEO4J_dbms_logs_query_threshold=0
  graphsplaining_service:
    restart: on-failure
    build:
      context: ./GraphsplainingService
      dockerfile: dev.Dockerfile
    volumes:
      - ./GraphsplainingService:/usr/src/app
    environment:
      # this is the graph that saves the explains
      - NEO4J_EXPLAIN_BOLT=bolt://neo4j_explain:17687
      - NEO4J_EXPLAIN_USER=neo4j
      - NEO4J_EXPLAIN_PASS=explain
      # this is the graph that is explained
      - NEO4J_MAIN_BOLT=bolt://neo4j_test:27687
      - NEO4J_MAIN_USER=neo4j
      - NEO4J_MAIN_PASS=explain
  graphsplaining_service_test:
    restart: on-failure
    build:
      context: ./GraphsplainingService
      dockerfile: dev.Dockerfile
    command: "npm test -- --watch"
    volumes:
      - ./GraphsplainingService:/usr/src/app
    environment:
      # this is the graph that saves the explains
      - NEO4J_EXPLAIN_BOLT=bolt://neo4j_explain:17687
      - NEO4J_EXPLAIN_USER=neo4j
      - NEO4J_EXPLAIN_PASS=explain
      # this is the graph that is explained
      - NEO4J_MAIN_BOLT=bolt://neo4j_test:27687
      - NEO4J_MAIN_USER=neo4j
      - NEO4J_MAIN_PASS=explain
volumes:
  # docker-compose will create these on start and they persist to keep graph data
  test_data:
  explain_data:
